src/OdeToFood/ViewComponents/GreetingViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Services;

namespace OdeToFood.ViewComponents
{
    public class GreetingViewComponent : ViewComponent
    {
        private IGreeter _greeter;

        public GreetingViewComponent(IGreeter greeter)
        {
            _greeter = greeter;
        }
        public Task<IViewComponentResult> InvokeAsync()
        {
            var model = _greeter.GetGreeting();
            return Task.FromResult<IViewComponentResult>(View("Default", model));
        }
    }
}

src/OdeToFood/ViewComponents/LoginLogoutViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace OdeToFood.ViewComponents
{
    public class LoginLogoutViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

src/OdeToFood/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/"> OdeToFood</a>
            </div>
            <div class="navbar-right">
                @await Component.InvokeAsync("LoginLogout")
            </div>
        </div>
    </nav>


    <div class="container">
        @RenderBody()
        <footer>
            @RenderSection("footer", required: false)
            @await Component.InvokeAsync("Greeting")
        </footer>
    </div>
    <environment names="Development">
        <script src="/node_modules/jquery/dist/jquery.js"></script>
        <script src="/node_modules/jquery-validation/dist/jquery.validate.js"></script>
        <script src="/node_modules/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    </environment>

    <environment names="Staging, Production">

    </environment>
</body>
</html>